CREATE TABLE IF NOT EXISTS "admin_user" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "email" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "password" VARBINARY(1137) NOT NULL,
  "first_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "last_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "phone" VARCHAR(20) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "analytic_data" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "type_id" INT NOT NULL,
  "ip_address" VARCHAR(50) COLLATE CASE_INSENSITIVE NOT NULL,
  "platform" VARCHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "browser" VARCHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "version" VARCHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "user_id" INT DEFAULT NULL,
  "candidate_id" INT DEFAULT NULL,
  "client_id" INT DEFAULT NULL,
  "test_id" INT DEFAULT NULL,
  "test_answer_id" INT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "analytic_type" (
  "id" INT NOT NULL ,
  "title" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("title")
)   ;

CREATE TABLE IF NOT EXISTS "application_event" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "application_id" INT NOT NULL,
  "read" SMALLINT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "application_event_description" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "text" VARCHAR(2048) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "application_identity_event" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "application_event_id" INT NOT NULL,
  "event_description_id" INT NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "candidate" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "candidate_description_last_id" INT DEFAULT NULL,
  "client_id" INT NOT NULL,
  "blocked" SMALLINT DEFAULT NULL,
  "is_new" SMALLINT DEFAULT NULL,
  "deleted" SMALLINT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "candidate_action_history" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "action_name_id" INT NOT NULL,
  "candidate_id" INT NOT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "candidate_action_name" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "title" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "candidate_candidate_tag" (
  "candidate_tag_id" INT DEFAULT NULL,
  "candidate_id" INT DEFAULT NULL
)  ;

CREATE TABLE IF NOT EXISTS "candidate_description" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "candidate_id" INT NOT NULL,
  "avatar_url" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "first_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "last_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "email" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "phone" VARCHAR(20) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "birth_date" DATE DEFAULT NULL,
  "comments" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "city" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "candidate_education" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "candidate_description_id" INT NOT NULL,
  "school" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "specialization" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "begin_date" DATE DEFAULT NULL,
  "end_date" DATE DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "candidate_email_invitation" (
  "id" INT NOT NULL ,
  "text" VARCHAR(max) COLLATE CASE_INSENSITIVE NOT NULL,
  "candidate_id" INT NOT NULL,
  "candidate_description_id" INT NOT NULL,
  "invite_key_id" INT NOT NULL,
  "vacancy_id" INT NOT NULL,
  "vacancy_description_history_id" INT NOT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "candidate_invite_key" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "key"VARBINARY(16) DEFAULT NULL,
  "base_url" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "application_id" INT NOT NULL,
  "used" SMALLINT DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("key")
)  ;

CREATE TABLE IF NOT EXISTS "candidate_status" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "title" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "candidate_tag" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "title" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "client_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("client_id","title")
)  ;

CREATE TABLE IF NOT EXISTS "candidate_user" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "email" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "password" VARBINARY(1137) NOT NULL,
  "candidate_id" INT NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "candidate_user_info" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "candidate_user_id" INT NOT NULL,
  "first_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "last_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "rights_and_obligation_id" INT NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "candidate_work_experience" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "candidate_description_id" INT NOT NULL,
  "begin_date" DATE NOT NULL,
  "end_date" DATE DEFAULT NULL,
  "title" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "company_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "description" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "client" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "country" VARCHAR(2) COLLATE CASE_INSENSITIVE NOT NULL,
  "number" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "name" VARCHAR(max) COLLATE CASE_INSENSITIVE NOT NULL,
  "license_url" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "industry_id" INT NOT NULL,
  "is_new" SMALLINT DEFAULT NULL,
  "blocked" SMALLINT DEFAULT NULL,
  "client_description_id" INT NOT NULL,
  "referral_user_id" INT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "client_description" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "name" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "description" VARCHAR(max) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "cv_upload" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "uuid" CHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "state" VARCHAR(32) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("uuid")
)   ;

CREATE TABLE IF NOT EXISTS "cv_upload_file" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "uuid" CHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "s3_url" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "s3_key" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "state" VARCHAR(32) COLLATE CASE_INSENSITIVE NOT NULL,
  "error_message" VARCHAR(2048) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "candidate_id" INT DEFAULT NULL,
  "client_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("uuid")
)   ;

CREATE TABLE IF NOT EXISTS "email_template" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "client_id" INT NOT NULL,
  "text" VARCHAR(max) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "industry" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "title" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "referral_bank_info" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "iban" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "bic" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "referral_company" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "vat" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "number_company" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "industry_id" INT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "referral_document" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "uuid" CHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "referral_user_id" INT NOT NULL,
  "type" VARCHAR(32) COLLATE CASE_INSENSITIVE NOT NULL,
  "document" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "document_s3_key" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("uuid")
)   ;

CREATE TABLE IF NOT EXISTS "referral_info" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "first_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "last_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "birthday" DATE DEFAULT NULL,
  "country" VARCHAR(2) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "referral_user" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "phone" VARCHAR(20) COLLATE CASE_INSENSITIVE NOT NULL,
  "email" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "password" VARBINARY(1137) NOT NULL,
  "key" CHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "right_and_obligation_id" INT NOT NULL,
  "referral_company_id" INT DEFAULT NULL,
  "referral_bank_info_id" INT NOT NULL,
  "referral_info_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("email")
)   ;

CREATE TABLE IF NOT EXISTS "rights_and_obligations" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "type" VARCHAR(32) COLLATE CASE_INSENSITIVE NOT NULL,
  "text" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "seller_document" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "seller_user_id" INT NOT NULL,
  "uuid" CHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "document_url" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "document_s3_key" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("uuid")
)   ;

CREATE TABLE IF NOT EXISTS "seller_info" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "seller_user_id" INT NOT NULL,
  "phone" VARCHAR(20) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "first_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "last_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "salary" float DEFAULT NULL,
  "num_id_card" VARCHAR(30) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "seller_invited" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "seller_user_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("seller_user_id","user_id")
)   ;

CREATE TABLE IF NOT EXISTS "seller_plan" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "seller_user_id" INT NOT NULL,
  "plan" INT NOT NULL,
  "calendar_segment" VARCHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "seller_user" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "email" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "password" VARBINARY(1137) NOT NULL,
  "deleted" SMALLINT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "temp_referral" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "right_and_obligation_id" INT DEFAULT NULL,
  "temp_referral_phone_id" INT DEFAULT NULL,
  "temp_referral_email_id" INT DEFAULT NULL,
  "referral_info_id" INT DEFAULT NULL,
  "referral_company_id" INT DEFAULT NULL,
  "referral_bank_info_id" INT DEFAULT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "temp_referral_document" (
  "id" INT NOT NULL ,
  "uuid" CHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "temp_referral_id" INT NOT NULL,
  "type" VARCHAR(32) COLLATE CASE_INSENSITIVE NOT NULL,
  "document" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "document_s3_key" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("uuid")
)  ;

CREATE TABLE IF NOT EXISTS "temp_referral_email" (
  "id" INT NOT NULL ,
  "email" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "code" VARCHAR(6) COLLATE CASE_INSENSITIVE NOT NULL,
  "active" SMALLINT DEFAULT NULL,
  "password" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "temp_referral_phone" (
  "id" INT NOT NULL ,
  "phone" VARCHAR(20) COLLATE CASE_INSENSITIVE NOT NULL,
  "code" VARCHAR(6) COLLATE CASE_INSENSITIVE NOT NULL,
  "active" SMALLINT DEFAULT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "temp_user" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "email" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "email_code" VARCHAR(6) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "email_active" SMALLINT DEFAULT NULL,
  "phone" VARCHAR(20) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "phone_code" VARCHAR(6) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "phone_active" SMALLINT DEFAULT NULL,
  "first_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "last_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "position" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "number_peoples" INT DEFAULT NULL,
  "client_name" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "country" VARCHAR(2) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "number_client" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "industry_id" INT DEFAULT NULL,
  "rights_id" INT DEFAULT NULL,
  "license_url" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "license_s3_key" VARCHAR(255) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "referral_user_id" INT DEFAULT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "test" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "type" VARCHAR(32) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "client_id" INT NOT NULL,
  "time" INT DEFAULT NULL,
  "title" VARCHAR(2047) COLLATE CASE_INSENSITIVE NOT NULL,
  "deleted" SMALLINT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "test_answer" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "question_id" INT NOT NULL,
  "score" INT DEFAULT NULL,
  "text" VARCHAR(max) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "test_question" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "number" INT DEFAULT NULL,
  "test_section_id" INT DEFAULT NULL,
  "text" VARCHAR(max) COLLATE CASE_INSENSITIVE NOT NULL,
  "outdated" SMALLINT DEFAULT NULL,
  "max_score" INT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "test_result" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "application_id" INT NOT NULL,
  "test_id" INT NOT NULL,
  "end_time" DATETIME DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "test_result_answer" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "test_result_id" INT NOT NULL,
  "test_answer_id" INT NOT NULL,
  "score" INT NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "test_section" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "test_id" INT NOT NULL,
  "title" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "description" VARCHAR(4095) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "max_score" INT DEFAULT NULL,
  "outdated" SMALLINT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "test_total_score_result" (
  "id" INT NOT NULL ,
  "test_result_id" INT NOT NULL,
  "test_section_id" INT NOT NULL,
  "total_score" INT DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("test_result_id","test_section_id")
)   ;

CREATE TABLE IF NOT EXISTS "test_vacancy" (
  "test_id" INT DEFAULT NULL,
  "vacancy_id" INT DEFAULT NULL
)  ;

CREATE TABLE IF NOT EXISTS "token_blocklist" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "jti" VARCHAR(36) COLLATE CASE_INSENSITIVE NOT NULL,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "token_logged_in" (
  "id" INT NOT NULL ,
  "sub" INT NOT NULL,
  "role" VARCHAR(32) COLLATE CASE_INSENSITIVE NOT NULL,
  "created" DATETIME NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "user" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "email" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "password" VARBINARY(1137) NOT NULL,
  "first_name" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "last_name" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "phone" VARCHAR(20) COLLATE CASE_INSENSITIVE NOT NULL,
  "img_url" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "is_new" SMALLINT DEFAULT NULL,
  "blocked" SMALLINT DEFAULT NULL,
  "rights_id" INT DEFAULT NULL,
  "client_id" INT NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "user_notification" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "type" VARCHAR(1024) COLLATE CASE_INSENSITIVE NOT NULL,
  "user_type" VARCHAR(32) COLLATE CASE_INSENSITIVE NOT NULL,
  "user_id" INT NOT NULL,
  "arguments" TEXT COLLATE CASE_SENSITIVE DEFAULT NULL ,
  "sent_status" TEXT COLLATE CASE_SENSITIVE DEFAULT NULL ,
  PRIMARY KEY ("id")
)  ;

CREATE TABLE IF NOT EXISTS "user_vacancy_group_subscription" (
  "vacancy_group_id" INT DEFAULT NULL,
  "user_id" INT DEFAULT NULL
)  ;

CREATE TABLE IF NOT EXISTS "user_vacancy_subscription" (
  "vacancy_id" INT DEFAULT NULL,
  "user_id" INT DEFAULT NULL
)  ;

CREATE TABLE IF NOT EXISTS "vacancy" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "vacancy_description_last_id" INT DEFAULT NULL,
  "vacancy_group_id" INT NOT NULL,
  "is_new" SMALLINT DEFAULT NULL,
  "blocked" SMALLINT DEFAULT NULL,
  "deleted" SMALLINT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "vacancy_application" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "candidate_id" INT NOT NULL,
  "vacancy_id" INT NOT NULL,
  "candidate_status_id" INT DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("candidate_id","vacancy_id")
)   ;

CREATE TABLE IF NOT EXISTS "vacancy_chat_message" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "text" VARCHAR(max) COLLATE CASE_INSENSITIVE NOT NULL,
  "application_event_id" INT NOT NULL,
  "candidate_user_id" INT DEFAULT NULL,
  "user_id" INT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "vacancy_description_history" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "title" VARCHAR(max) COLLATE CASE_INSENSITIVE NOT NULL,
  "salary_from" INT NOT NULL,
  "salary_to" INT NOT NULL,
  "closing_date" DATE DEFAULT NULL,
  "description" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "skills" VARCHAR(max) COLLATE CASE_INSENSITIVE NOT NULL,
  "img_url" VARCHAR(max) COLLATE CASE_INSENSITIVE DEFAULT NULL,
  "vacancy_id" INT NOT NULL,
  "client_description_id" INT NOT NULL,
  PRIMARY KEY ("id")
)   ;

CREATE TABLE IF NOT EXISTS "vacancy_group" (
  "created" DATETIME NOT NULL,
  "updated" DATETIME NOT NULL,
  "id" INT NOT NULL ,
  "title" VARCHAR(255) COLLATE CASE_INSENSITIVE NOT NULL,
  "client_id" INT NOT NULL,
  "client_description_id" INT NOT NULL,
  "deleted" SMALLINT DEFAULT NULL,
  PRIMARY KEY ("id")
)   ;
